name: mil-game-6feature
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - git
  - ffmpeg
  - libsndfile
  - pip:
      - -r requirements.txt
      - torch==2.10.0
      - torchvision==0.25.0
      - torchaudio==2.10.0
      - matplotlib
      - seaborn
      - jupyter
      - notebook
      - ipykernel
      - yt-dlp
      - demucs
      - faster-whisper
      - sentence-transformers
      - xgboost
